
var DZ={SETTING_HOST_SITE:'http://www.deezer.com',SETTING_HOST_CONNECT:'http://connect.deezer.com',SETTING_HOST_API:'http://api.deezer.com/2.0',WIDGET_TYPE_PLAYER:'dzplayer',DEBUG:false,dz_root:null,token:null,tokenExpire:null,tokenExpireTimeout:null,app_id:null,user_id:null,channelUrl:null,fb_logged:false,initialized:false,has_player:false,_override_pp:function(){DZ.SETTING_HOST_SITE="http://preprod.deezer.com";DZ.SETTING_HOST_CONNECT="http://preprod-connect.deezer.com";DZ.SETTING_HOST_API="http://preprod-api.deezer.com/2.0";},checkChannel:function(){},init:function(options){try{DZ.initException();if(typeof(options)!='undefined'&&options.initChannel)return this.initChannel(options);DZ.log("init",options);DZ.dz_root=document.getElementById('dz-root');if(DZ.dz_root==null){throw DZ.Exception('dz-root');}
DZ.dz_root.style.height="0px";DZ.dz_root.style.width="0px";if(typeof(options)=='undefined'||typeof(options.channelUrl)=='undefined')throw DZ.Exception('channelUrl');this.channelUrl=options.channelUrl;DZ.communication.init();DZ.initialized=true;if(options.initPlayer)return this.player_controler.init(options);if(options.appId)this.app_id=options.appId;if(typeof(options.player)!='undefined'&&(options.player===true||typeof(options.player)=='object')){DZ.has_player=true;DZ.player.loadPlayer(options);}}catch(e){DZ.catchException(e);}},login:function(callback,opts){try{if(!DZ.initialized)throw DZ.Exception('init');DZ.Event.suscribe('login',DZ.loginCommonCallback,true);if(typeof(callback)=='function'){DZ.Event.suscribe('login',callback,true);}
var screen_x=typeof window.screenX!='undefined'?window.screenX:window.screenLeft;var screen_y=typeof window.screenY!='undefined'?window.screenY:window.screenTop;var screen_w=typeof window.outerWidth!='undefined'?window.outerWidth:document.documentElement.clientWidth;var screen_h=typeof window.outerHeight!='undefined'?window.outerHeight:(document.documentElement.clientHeight-22);var popup_w=645;var popup_h=430;var popup_left=screen_x+(screen_w/2)-(popup_w/2);var popup_top=screen_y+(screen_h/2)-(popup_h/2);var src=DZ.SETTING_HOST_CONNECT+"/oauth/auth.php?";var arg=new Array();arg.push("app_id="+this.app_id);arg.push("format=popup");arg.push("redirect_uri="+this.channelUrl);arg.push("response_type=token");var opts=opts||{};if(opts.perms&&opts.perms!=""){arg.push("perms="+opts.perms);}
if(opts.fb_login){arg.push("fblogin=true");}
src=src+arg.join('&');window.open(src,"login",'top='+popup_top+',left='+popup_left+',width='+popup_w+',height='+popup_h+',location=yes',true);}catch(e){DZ.catchException(e);}},getLoginStatus:function(callback){try{if(!DZ.initialized)throw DZ.Exception('init');DZ.Event.suscribe('login',DZ.loginCommonCallback,true);if(typeof(callback)=='function'){DZ.Event.suscribe('login',callback,true);}
var connect_frame=document.createElement('iframe');connect_frame.style.display="none";var src=DZ.SETTING_HOST_CONNECT+"/oauth/auth.php?";var arg=new Array();arg.push("app_id="+this.app_id);arg.push("format=channel");arg.push("redirect_uri="+this.channelUrl);arg.push("response_type=token");src=src+arg.join('&');connect_frame.onload=function(){document.getElementById('dz-root').removeChild(connect_frame);};connect_frame.src=src;document.getElementById('dz-root').appendChild(connect_frame);}catch(e){DZ.catchException(e);}},loginCommonCallback:function(response){try{if(response.error){setTimeout(function(){throw DZ.Exception();},0);return;}
if(response.authResponse!=null){DZ.token=response.authResponse.accessToken;DZ.tokenExpire=response.authResponse.expire;DZ.user_id=response.userID;if(DZ.tokenExpire!=0){DZ.tokenExpireTimeout=window.setTimeout(function(){DZ.getLoginStatus();},(DZ.tokenExpire)*1000);}
if(DZ.has_player){DZ.player.onLogin();}}}catch(e){DZ.catchException(e);}},logout:function(){try{if(!DZ.initialized)throw DZ.Exception('init');var logout_frame=document.createElement('iframe');logout_frame.style.display="none";var src=DZ.SETTING_HOST_CONNECT+"/logout.php?";var arg=new Array();src=src+arg.join('&');logout_frame.onload=function(){document.getElementById('dz-root').removeChild(logout_frame);DZ.tokenExpireTimeout=null;DZ.token=null;DZ.tokenExpire=null;DZ.user_id=null;if(DZ.has_player){DZ.player.onLogout();}};logout_frame.src=src;document.getElementById('dz-root').appendChild(logout_frame);}catch(e){DZ.catchException(e);}},initChannel:function(){try{var hashSplitted=unescape(window.document.location.hash).substr(1).split('|');if(hashSplitted.length>1){var type=hashSplitted[0];if(type=="channel"){DZ.communication.proxy_channel(hashSplitted);}else if(type=='token'){var windowroot=window.opener||window.top;var access_token=hashSplitted[1];var authResponse={authResponse:{accessToken:null,expire:null},status:'notconnected',userID:null};if(access_token!='null'&&access_token!='exception'){var token=access_token.split('&');var expire=token[1].split('=')[1]*1;token=token[0].split('=')[1];authResponse.authResponse.accessToken=token;authResponse.authResponse.expire=expire;authResponse.status='connected';authResponse.userID=hashSplitted[2];}else{authResponse.status=hashSplitted[2];if(access_token=='exception')authResponse.error=true;authResponse.authResponse=null;}
if(typeof(windowroot.DZ)=='undefined'){throw DZ.Exception("XD_ERROR");}
windowroot.DZ.Event.triggerEvent({evt:'login',args:authResponse});window.close();}}}catch(e){DZ.catchException(e);}},widget:{getPlayer:function(options){var options=options||{};if(typeof(options.type)=='undefined'||typeof(options.id)=='undefined'){throw"You must define a type AND an id ! (options.type, options.id)";return false;}
var width=options.width||400;var height=options.height||230;var playlist='true';var cover='true';var scover='true';var autoplay='false';if(typeof(options.playlist)!='undefined')playlist=options.playlist?'true':'false';if(typeof(options.cover)!='undefined')cover=options.cover?'true':'false';if(typeof(options.scover)!='undefined')scover=options.scover?'true':'false';if(typeof(options.autoplay)!='undefined')autoplay=options.autoplay?'true':'false';var code='<iframe scrolling="no" frameborder="0" allowTransparency="true" src="'
+DZ.SETTING_HOST_SITE+'/fr/plugins/player?'+'autoplay='+autoplay+'&playlist='+playlist+'&width='+width+'&height='+height+'&scover='+autoplay+'&type='+options.type+'&id='+options.id+'&title='+'" width="'+width+'" height="'+height+'"></iframe>';return code;}}};;
DZ.error=function(e){if(typeof(console)=='undefined'||typeof(console.error)=='undefined'){return;}
if(typeof(e)!='object'){console.error(e);}else{console.error(e);console.error(e.stack);}}
DZ.log=function(){if(DZ.DEBUG&&typeof(console)!='undefined'&&typeof(console.log)!='undefined'){console.log(arguments);}};DZ.catchException=function(e){DZ.error(e);};DZ.initException=function(){if(typeof(console)=='undefined'||typeof(console.log)=='undefined'||typeof(console.error)=='undefined'){window.console={log:function(){return;},error:function(){return;var args=arguments;var outputString=[];for(i=0;i<args.length;i++){outputString.push(args[i]);}
alert("Error : "+outputString.join(' | '));}};}};DZ.Exception=function(type){var message;if(typeof(type)!='undefined'){message=typeof(DZ.Exceptions[type])=='undefined'?type:DZ.Exceptions[type];}else{message=DZ.Exceptions.common;}
if(DZ.DEBUG){var exception=new Error(message);if(typeof(exception.stack)!='undefined'){exception.stack=exception.stack.replace('Error:',DZ.Exceptions.type+':')}
return exception;}else{return message;}};DZ.Exceptions={type:"DzError",common:"An error has occured, please retry your action",init:"DZ has not been initialized, you must call DZ.init(options) first !",channelUrl:"You must define a channelUrl !",'dz-root':"dz-root is not defined",XD_ERROR:"Cannot access to top window, Your channel domain, protocol and port must match with your top frame.",PLAYER_NOT_LOADED:"You must load a player first !",COMMUNICATION_SECURITY:"SECURITY EXCEPTION, you are not supposed to use this function !"};;
DZ.api=function(){try{var path=null,request_method='get',args=null,callback=false;switch(arguments.length){case 1:path=arguments[0];break;case 2:path=arguments[0];callback=arguments[1];break;case 3:path=arguments[0];if(typeof(arguments[1])=='string'){request_method=arguments[1];}else{args=arguments[1];}
callback=arguments[2];break;case 4:path=arguments[0];request_method=arguments[1];args=arguments[2];callback=arguments[3];break;default:break;}
var callback=callback||function(){};if(path==null||path==""){callback({error:'no path defined'});return false;}
DZ.SIMPLE_API.apiCall(path,request_method,args,callback);}catch(e){DZ.catchException(e);}};DZ.SIMPLE_API={callbacks:{},apiCall:function(path,request_method,args,callback){try{if(path[0]!="/")path="/"+path;var path_splitted=path.split('?');var path_args=new Array();if(path_splitted.length>1){path=path_splitted[0];path_args=path_splitted[1].split('&');}
var path=DZ.SETTING_HOST_API+path;if(request_method!='get')path_args.push("request_method="+request_method);if(args!=null){for(var property in args){path_args.push(property+"="+escape(args[property]));}}
path_args.push("output=jsonp");if(DZ.token!=null)path_args.push("access_token="+DZ.token);DZ.request._send({path:path,path_args:path_args,callback:callback,callback_name:"callback"});}catch(e){DZ.catchException(e);}}};;
DZ.Event={MUSIC_END:'music.end',MUSIC_START:'music.start',PLAYER_LOADED:'player.loaded',player:{LOADED:'player_loaded',PLAY:'player_play',PAUSED:'player_paused',POSITION_CHANGED:'player_position',VOLUME_CHANGED:'volume_changed',BUFFERING_CHANGED:'player_buffering',TRACKS_LOADED:'player_track_loaded',CURRENT_TRACK:'current_track'},callbacks:{'music.end':new Array(),'music.start':new Array(),'player.loaded':new Array()},suscribe:function(evt,callback,once){try{if(!DZ.initialized)throw DZ.Exception('init');if(typeof(callback)=='object')return DZ.Event.suscribeList(evt,callback,once);if(once)callback.once=true;switch(evt){case DZ.Event.MUSIC_END:case DZ.Event.MUSIC_START:DZ.Event.callbacks[evt].push(callback);break;default:if(typeof(DZ.Event.callbacks[evt])=='undefined')DZ.Event.callbacks[evt]=new Array();DZ.Event.callbacks[evt].push(callback);break;}}catch(e){DZ.catchException(e);}},subscribe:function(evt,callback,once){DZ.Event.suscribe(evt,callback,once);},suscribeList:function(evt,callbacks,once){try{for(var i=0;i<callbacks.length;i++){DZ.Event.suscribe(evt,callbacks[i],once);}}catch(e){DZ.catchException(e);}},unsuscribe:function(evt){try{if(!DZ.initialized)throw DZ.Exception('init');if(!evt||typeof(DZ.Event.callbacks[evt])=='undefined')return false;DZ.Event.callbacks[evt]=new Array();}catch(e){DZ.catchException(e);}},unsubscribe:function(evt){DZ.Event.unsuscribe(evt);},eventTriggered:function(response){try{return DZ.EVENT.triggerEvent(response);}catch(e){DZ.catchException(e);}},triggerEvent:function(response){try{var args=(typeof(response.args)=='undefined')?null:response.args;if(response.evt&&DZ.Event.callbacks[response.evt]){var nbToExecute=DZ.Event.callbacks[response.evt].length;for(var i=0;i<nbToExecute;i++){DZ.Event.callbacks[response.evt][i](args,response.evt);DZ.Event.callbacks[response.evt][i].executed=true;}
var cleanedCallbacks=new Array();for(var i=0;i<DZ.Event.callbacks[response.evt].length;i++){if(!DZ.Event.callbacks[response.evt][i].executed||!DZ.Event.callbacks[response.evt][i].once)
cleanedCallbacks.push(DZ.Event.callbacks[response.evt][i]);}
DZ.Event.callbacks[response.evt]=cleanedCallbacks;}}catch(e){DZ.catchException(e);}}};;
DZ.communication={postMessage:false,testPostMessage:function(){if(typeof(window.postMessage)=='undefined'||typeof(window.postMessage.call)=='undefined'){return false;}
if(typeof(window.navigator)=='undefined'||typeof(window.navigator.userAgent)=='undefined'){return false;}
if(window.navigator.userAgent.toLowerCase().indexOf('firefox/3.6')!=-1){return false;}
return true;},init:function(){try{if(DZ.communication.testPostMessage()){DZ.communication.postMessage=true;if(window.addEventListener){window.addEventListener("message",DZ.communication.receive,false);}else{window.attachEvent("onmessage",DZ.communication.receive);}}}catch(e){DZ.catchException(e);}},proxy_send:function(message,domain){try{var channelUrl=DZ.channelUrl;if(domain=="deezer")channelUrl=(DZ.SETTING_HOST_SITE)+"/plugins/channel.php";channelUrl=channelUrl+"#channel|"+DZ.JSON.stringify(message);var iframeChannel=window.document.createElement('iframe');iframeChannel.src=channelUrl;iframeChannel.style.display="none";iframeChannel.onload=function(){window.document.getElementById('dz-root').removeChild(iframeChannel);};window.document.getElementById('dz-root').appendChild(iframeChannel);}catch(e){DZ.catchException(e);}},proxy_channel:function(hashSplitted){try{var type=hashSplitted[0];var message=eval("("+hashSplitted[1]+")");if(typeof(message)=='undefined')return false;var target=eval("window.parent."+message.framePath);target.DZ.communication.receive(message);}catch(e){DZ.catchException(e);}},send:function(framePath,method,args,domain){try{var domain=domain||"app";var message={method:method,args:args};if(DZ.communication.postMessage){var iframeToSend=null;if(framePath=='frames.dzplayer'){iframeToSend=DZ.player.player_iframe.contentWindow;}else{iframeToSend=eval("window."+framePath);}
var blu=iframeToSend.postMessage(message,"*");}else{message.framePath=framePath;DZ.communication.proxy_send(message,domain);}}catch(e){DZ.catchException(e);}},receive:function(evt){try{var data=evt;if(evt.data)data=evt.data;if(typeof(data.method)=='undefined')return false;var fct=data.method.split('.');if(fct.length>0&&fct[0]=='DZ'){var fctToCall=window;for(i=0;i<fct.length;i++){if(typeof(fctToCall[fct[i]])!='undefined'){fctToCall=fctToCall[fct[i]];}else{throw DZ.Exception('COMMUNICATION_SECURITY');return false;}}
if(typeof(fctToCall)!='function'){throw DZ.Exception('COMMUNICATION_SECURITY');}}else{throw DZ.Exception('COMMUNICATION_SECURITY');return false;}
fctToCall(data.args);}catch(e){DZ.catchException(e);}}};;
DZ.JSON={stringify:function stringify(arg){var c,i,l,s='',v;switch(typeof arg){case'object':if(arg){if(arg.constructor==Array){for(i=0;i<arg.length;++i){v=stringify(arg[i]);if(s){s+=',';}
s+=v;}
return'['+s+']';}else if(typeof arg.toString!='undefined'){for(i in arg){v=stringify(arg[i]);if(typeof v!='function'){if(s){s+=',';}
s+=stringify(i)+':'+v;}}
return'{'+s+'}';}}
return'null';case'number':return isFinite(arg)?String(arg):'null';case'string':l=arg.length;s='"';for(i=0;i<l;i+=1){c=arg.charAt(i);if(c>=' '){if(c=='\\'||c=='"'){s+='\\';}
s+=c;}else{switch(c){case'\b':s+='\\b';break;case'\f':s+='\\f';break;case'\n':s+='\\n';break;case'\r':s+='\\r';break;case'\t':s+='\\t';break;default:c=c.charCodeAt();s+='\\u00'+Math.floor(c/16).toString(16)+
(c%16).toString(16);}}}
return s+'"';case'boolean':return String(arg);default:return'null';}},parse:function(text){var at=0;var ch=' ';function error(m){throw{name:'JSONError',message:m,at:at-1,text:text};}
function next(){ch=text.charAt(at);at+=1;return ch;}
function white(){while(ch){if(ch<=' '){next();}else if(ch=='/'){switch(next()){case'/':while(next()&&ch!='\n'&&ch!='\r'){}
break;case'*':next();for(;;){if(ch){if(ch=='*'){if(next()=='/'){next();break;}}else{next();}}else{error("Unterminated comment");}}
break;default:error("Syntax error");}}else{break;}}}
function string(){var i,s='',t,u;if(ch=='"'){outer:while(next()){if(ch=='"'){next();return s;}else if(ch=='\\'){switch(next()){case'b':s+='\b';break;case'f':s+='\f';break;case'n':s+='\n';break;case'r':s+='\r';break;case't':s+='\t';break;case'u':u=0;for(i=0;i<4;i+=1){t=parseInt(next(),16);if(!isFinite(t)){break outer;}
u=u*16+t;}
s+=String.fromCharCode(u);break;default:s+=ch;}}else{s+=ch;}}}
error("Bad string");}
function array(){var a=[];if(ch=='['){next();white();if(ch==']'){next();return a;}
while(ch){a.push(value());white();if(ch==']'){next();return a;}else if(ch!=','){break;}
next();white();}}
error("Bad array");}
function object(){var k,o={};if(ch=='{'){next();white();if(ch=='}'){next();return o;}
while(ch){k=string();white();if(ch!=':'){break;}
next();o[k]=value();white();if(ch=='}'){next();return o;}else if(ch!=','){break;}
next();white();}}
error("Bad object");}
function number(){var n='',v;if(ch=='-'){n='-';next();}
while(ch>='0'&&ch<='9'){n+=ch;next();}
if(ch=='.'){n+='.';while(next()&&ch>='0'&&ch<='9'){n+=ch;}}
v=+n;if(!isFinite(v)){error("Bad number");}else{return v;}}
function word(){switch(ch){case't':if(next()=='r'&&next()=='u'&&next()=='e'){next();return true;}
break;case'f':if(next()=='a'&&next()=='l'&&next()=='s'&&next()=='e'){next();return false;}
break;case'n':if(next()=='u'&&next()=='l'&&next()=='l'){next();return null;}
break;}
error("Syntax error");}
function value(){white();switch(ch){case'{':return object();case'[':return array();case'"':return string();case'-':return number();default:return ch>='0'&&ch<='9'?number():word();}}
return value();}};;
DZ.player={loaded:false,player_iframe:null,player_type:null,onLoad:function(settings){DZ.player.loaded=true;DZ.Event.triggerEvent({evt:DZ.Event.player.LOADED,args:settings});},_cachee:function(){},receiveEvent:function(args){try{var event=args.evt;var value=typeof(args.val)=='undefined'?null:args.val;if(typeof(DZ.Event.player[event]!='undefined')){if(event=='TRACKS_LOADED'){DZ.player._core.onLoadedInPlayer(value);var songs=value.tracks;DZ.Event.triggerEvent({evt:DZ.Event.player[event]+"_"+value.type+'_'+value.id,args:{tracks:songs}});}else if(event=='CURRENT_TRACK'){DZ.player._core.onCurrentSong(value);var track=DZ.player._core.getCurrentSong();DZ.Event.triggerEvent({evt:DZ.Event.player[event],args:{track:track,index:DZ.player._core.index}});}else if(event=='NOTIFY'){DZ.notify.display(value);}else if(event=='FB_LOGGED'){DZ.fb_logged=true;}else if(event=='PLAY'||event=='PAUSED'){DZ.Event.triggerEvent({evt:DZ.Event.player[event],args:DZ.Event.player[event]});}else{DZ.Event.triggerEvent({evt:DZ.Event.player[event],args:value});}}}catch(e){DZ.catchException(e);}},attachEvents:function(){DZ.Event.suscribe(DZ.Event.player.LOADED,function(){},true);},loadPlayer:function(options){try{if(typeof(options.player)=='undefined'||typeof(options.appId)=='undefined'){throw"An error has occured !";}
var appId=options.appId;options=options.player;var default_options={playlist:false,cover:false};options=typeof(options)!='object'?{}:options;DZ.util.extend(default_options,options);options.drawPlayer=false;if(typeof(options)!='undefined'&&typeof(options.container)!='undefined'){options.drawPlayer=true;}
if(options.drawPlayer&&document.getElementById(options.container)==null){throw"id container does not exist !";return false;}
DZ.player.attachEvents();if(typeof(options.onload)=='function'){DZ.Event.suscribe('player_loaded',options.onload);}
DZ.player.player_type='light';DZ.player.player_iframe=document.createElement('iframe');DZ.player.player_iframe.id="dzplayer";DZ.player.player_iframe.name="dzplayer";var src=DZ.SETTING_HOST_SITE+"/plugins/player.php?";var arg=new Array();arg.push("channel="+DZ.channelUrl);arg.push("app_id="+appId);var iframeId="dz-root";if(options.drawPlayer){if(typeof(options.cover)!='undefined')arg.push("cover="+(options.cover?'true':'false'));if(typeof(options.playlist)!='undefined')arg.push("playlist="+(options.playlist?'true':'false'));if(typeof(options.width)!='undefined')arg.push("width="+options.width);if(typeof(options.height)!='undefined')arg.push("height="+options.height);if(typeof(options.format)!='undefined')arg.push("format="+options.format);iframeId=options.container;DZ.player.player_iframe.style.display="block";DZ.player.player_iframe.style.height=(typeof(options.height)!='undefined')?(options.height+'px'):"100%";DZ.player.player_iframe.style.width=(typeof(options.width)!='undefined')?(options.width+'px'):"100%";}else{DZ.player.player_iframe.style.position="absolute";DZ.player.player_iframe.style.width="10px";DZ.player.player_iframe.style.height="20px";DZ.player.player_iframe.style.border="none";arg.push("emptyPlayer=true");}
src=src+arg.join('&');DZ.player.player_iframe.src=src;document.getElementById(iframeId).appendChild(DZ.player.player_iframe);}catch(e){DZ.catchException(e);}},loadWidget:function(options){try{DZ.player.attachEvents();DZ.player.player_type='widget';var options=options||{};if(typeof(options.containerId)=='undefined'){throw"You must define a containerId (options.containerId) !";return false;}
var container=document.getElementById(options.containerId);if(typeof(container)=='undefined'||container==null){throw"The container you defined doesn't exists !";return false;}
var width=options.width||400;var height=options.height||230;var playlist='true';var cover='true';var scover='true';var autoplay='false';if(typeof(options.playlist)!='undefined')playlist=options.playlist?'true':'false';if(typeof(options.cover)!='undefined')cover=options.cover?'true':'false';if(typeof(options.scover)!='undefined')scover=options.scover?'true':'false';if(typeof(options.autoplay)!='undefined')autoplay=options.autoplay?'true':'false';var src=DZ.SETTING_HOST_SITE+'/fr/plugins/player?'+'autoplay='+autoplay+'&playlist='+playlist+'&width='+width+'&height='+height+'&scover='+autoplay+'&title=';src+="&type=songList";src+="&songIds="+options.songIds.join(',');src+="&dzwidget=true";src+="&channel="+DZ.channelUrl;DZ.player.player_iframe=document.createElement('iframe');DZ.player.player_iframe.id="dzplayer";DZ.player.player_iframe.src=src;DZ.player.player_iframe.style.width=width+"px";DZ.player.player_iframe.style.height=height+"px";DZ.player.player_iframe.style.border="none";container.appendChild(DZ.player.player_iframe);}catch(e){DZ.catchException(e);}},onLogin:function(){DZ.communication.send("frames.dzplayer","DZ.player_controler.onLogin",null,'deezer');},onLogout:function(){DZ.communication.send("frames.dzplayer","DZ.player_controler.onLogout",null,'deezer');},play:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'play'},'deezer');}catch(e){DZ.catchException(e);}},pause:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'pause'},'deezer');}catch(e){DZ.catchException(e);}},next:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'next'},'deezer');}catch(e){DZ.catchException(e);}},prev:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'prev'},'deezer');}catch(e){DZ.catchException(e);}},seek:function(value){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'seek',value:(value/100)},'deezer');}catch(e){DZ.catchException(e);}},setVolume:function(value){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
if(!DZ.player._core.isRunning())return false;DZ.communication.send("frames.dzplayer","DZ.player_controler.doAction",{command:'volume',value:(value)},'deezer');}catch(e){DZ.catchException(e);}},beforePlay:function(){if(DZ.fb_logged&&DZ.token==null){DZ.login(function(){},{fb_login:true});DZ.fb_logged=false;}},get_play_fct_args:function(args){try{switch(args.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}}catch(e){DZ.catchException(e);}},playPlaylist:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
DZ.player.beforePlay();if(arguments.length==0||(typeof(arguments[0])!='string'&&typeof(arguments[0])!='number')){return false;}
var playlist_id=arguments[0];var index=0;var callback=function(){};switch(arguments.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}
DZ.Event.suscribe(DZ.Event.player.TRACKS_LOADED+"_playPlaylist_"+playlist_id,[function(){},callback],true);DZ.player._core.setType("playPlaylist",playlist_id);DZ.communication.send("frames.dzplayer","DZ.player_controler.playPlaylist",{playlist_id:playlist_id,index:index,autoplay:true},'deezer');return true;}catch(e){DZ.catchException(e);}},playAlbum:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
DZ.player.beforePlay();if(arguments.length==0||(typeof(arguments[0])!='string'&&typeof(arguments[0])!='number')){return false;}
var album_id=arguments[0];var index=0;var callback=function(){};switch(arguments.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}
DZ.Event.suscribe(DZ.Event.player.TRACKS_LOADED+"_playAlbum_"+album_id,[function(){},callback],true);DZ.player._core.setType("playAlbum",album_id);DZ.communication.send("frames.dzplayer","DZ.player_controler.playAlbum",{album_id:album_id,index:index,autoplay:true},'deezer');}catch(e){DZ.catchException(e);}},playRadio:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
DZ.player.beforePlay();if(arguments.length==0||(typeof(arguments[0])!='string'&&typeof(arguments[0])!='number')){return false;}
var radio_id=arguments[0];var index=0;var callback=function(){};switch(arguments.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}
DZ.Event.suscribe(DZ.Event.player.TRACKS_LOADED+"_playRadio_"+radio_id,[function(){},callback],true);DZ.player._core.setType("playRadio",radio_id);DZ.communication.send("frames.dzplayer","DZ.player_controler.playRadio",{radio_id:radio_id,index:0,autoplay:true},'deezer');}catch(e){DZ.catchException(e);}},playSmartRadio:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
DZ.player.beforePlay();if(arguments.length==0||(typeof(arguments[0])!='string'&&typeof(arguments[0])!='number')){return false;}
var radio_id=arguments[0];var index=0;var callback=function(){};switch(arguments.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}
DZ.Event.suscribe(DZ.Event.player.TRACKS_LOADED+"_playSmartRadio_"+radio_id,[function(){},callback],true);DZ.player._core.setType("playSmartRadio",radio_id);DZ.communication.send("frames.dzplayer","DZ.player_controler.playSmartRadio",{radio_id:radio_id,index:index,autoplay:true},'deezer');}catch(e){DZ.catchException(e);}},playTracks:function(){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
DZ.player.beforePlay();if(arguments.length==0||typeof(arguments[0])!='object'){return false;}
var trackList=arguments[0];var index=0;var callback=function(){};switch(arguments.length){case 1:break;case 2:if(typeof(arguments[1])=='function'){callback=arguments[1];}else if(typeof(arguments[1])=='number'){index=arguments[1];}
break;case 3:if(typeof(arguments[1])=='number')index=arguments[1];if(typeof(arguments[2])=='function')callback=arguments[2];break;}
trackList=trackList.join('|');DZ.player._core.setType("playTracks",trackList);DZ.communication.send("frames.dzplayer","DZ.player_controler.playTracks",{trackList:trackList,index:index,autoplay:true},'deezer');}catch(e){DZ.catchException(e);}},setTrackList:function(songList,callback){try{if(!DZ.player.loaded){throw DZ.Exception('PLAYER_NOT_LOADED');return false;}
var callback=callback||function(){};DZ.Event.suscribe(DZ.Event.player.TRACKS_LOADED,callback,true);DZ.communication.send("frames.dzplayer","DZ.player_controler.setSongList",songList,'deezer');}catch(e){DZ.catchException(e);}},getTrackList:function(){return DZ.player._core.getTrackList();},getCurrentSong:function(){return DZ.player._core.getCurrentSong();},getCurrentIndex:function(){return DZ.player._core.index;},_core:{tracks:null,idToIndex:null,index:null,type:null,id:null,isRunning:function(){return(DZ.player._core.tracks!=null&&DZ.player._core.index!=null&&DZ.player._core.type!=null);},setType:function(type,id){DZ.player._core.type=type;DZ.player._core.id=id;},onLoadedInPlayer:function(data){if(data.type!=DZ.player._core.type||data.id!=DZ.player._core.id)return false;DZ.player._core.tracks=data.tracks;DZ.player._core.idToIndex=[];for(i=0;i<DZ.player._core.tracks.length;i++){DZ.player._core.idToIndex[DZ.player._core.tracks[i].id]=i;}
DZ.player._core.index=0;},onCurrentSong:function(sng_id){DZ.log("on current song");if(typeof(DZ.player._core.idToIndex[sng_id])!='undefined')DZ.player._core.index=DZ.player._core.idToIndex[sng_id];DZ.log("on current song : DZ.player._core.index = ",DZ.player._core.index);},getTrackList:function(){if(!DZ.player._core.isRunning())return[];return DZ.player._core.tracks;},getCurrentSong:function(){var core=DZ.player._core;DZ.log("getCurrentCong ",core.isRunning(),core.index,core.tracks.length);if(!core.isRunning()||core.index<0||core.index>=core.tracks.length)return null;return core.tracks[core.index];},next:function(){},prev:function(){}}};;
DZ.player_controler={init:function(options){try{DZ.player_controler.suscribeEvents();options.widgetOptions.drawPlayer=typeof(options.widgetOptions.emptyPlayer)=='undefined';widget.init(options);return true;}catch(e){DZ.catchException(e);}},onPlayerLoaded:function(){try{DZ.player_controler.playerLoaded=true;DZ.communication.send("parent","DZ.player.onLoad",{volume:dzPlayer.getVolume(),shuffle:dzPlayer.isShuffle()});}catch(e){DZ.catchException(e);}},onLogin:function(){user.userLogin(function(){widget.initRestriction();});},onLogout:function(){dzPlayer.setForbiddenListen(true);user.logout(true,false);widget.initRestriction();},convertData:function(data){try{var track={};track.id=data.SNG_ID;track.duration=data.DURATION;track.title=data.SNG_TITLE;track.artist={id:data.ART_ID,name:data.ART_NAME};track.album={id:data.ALB_ID,title:data.ALB_TITLE}
return track;}catch(e){DZ.catchException(e);}},suscribeEvents:function(){try{Events.suscribe(Events.player_widget.loaded,DZ.player_controler.onPlayerLoaded);Events.suscribe(Events.player.play,function(evt,val){DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'PLAY'});});Events.suscribe(Events.player.resume,function(evt,val){DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'PLAY'});});Events.suscribe(Events.player.paused,function(evt,val){DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'PAUSED'});});Events.suscribe(Events.player.position,function(evt,val){if(val==null)val=0;DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'POSITION_CHANGED',val:[val,dzPlayer.duration]});});Events.suscribe(Events.player.volume,function(evt,val){if(val==null)val=0;DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'VOLUME_CHANGED',val:Math.round(val*100)});});Events.suscribe(Events.player.pourcentLoaded,function(evt,val){DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'BUFFERING_CHANGED',val:val});});Events.suscribe(Events.player.displayCurrentSong,function(evt,val){if(val==null)val=0;DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'CURRENT_TRACK',val:dzPlayer.getCurrentSongInfo().SNG_ID});});Events.suscribe('player_track_loaded',function(evt,data){var widgetLines=data.tracks;var tracks=new Array();for(i=0;i<widgetLines.length;i++){var track=DZ.player_controler.convertData(widgetLines[i]);tracks.push(track);}
data.tracks=tracks;DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'TRACKS_LOADED',val:data});});Events.suscribe(Events.player_widget.displayLayer,function(evt,data){DZ.communication.send("parent","DZ.player.receiveEvent",{evt:'NOTIFY',val:data});});return true;}catch(e){DZ.catchException(e);}},doAction:function(args){try{var command=args.command;var value=args.value||null;playercontrol.doAction(command,[value]);}catch(e){DZ.catchException(e);}},playTracks:function(arg){try{DZ.log("player_control.playTracks",arg);widget.loadSongs(arg.trackList.split('|'),function(tracks){Events.trigger("player_track_loaded",{tracks:tracks,type:'playTracks',id:arg.trackList});},arg.autoplay,arg.index);}catch(e){DZ.catchException(e);}},playPlaylist:function(arg){try{DZ.log("playPlaylist",arg);widget.loadPlaylist(arg.playlist_id,function(tracks){Events.trigger("player_track_loaded",{tracks:tracks,type:'playPlaylist',id:arg.playlist_id});},arg.autoplay,arg.index);}catch(e){DZ.catchException(e);}},playAlbum:function(arg){try{DZ.log("playPlaylist",arg);widget.loadAlbum(arg.album_id,function(tracks){Events.trigger("player_track_loaded",{tracks:tracks,type:'playAlbum',id:arg.album_id});},arg.autoplay,arg.index);}catch(e){DZ.catchException(e);}},playRadio:function(arg){try{DZ.log("playRadio",arg);widget.loadRadio('radio-'+arg.radio_id,function(tracks){Events.trigger("player_track_loaded",{tracks:tracks,type:'playRadio',id:arg.radio_id});},arg.autoplay,arg.index);}catch(e){DZ.catchException(e);}},playSmartRadio:function(arg){try{DZ.log("playRadio",arg);widget.loadRadio('artist-'+arg.radio_id,function(tracks){Events.trigger("player_track_loaded",{tracks:tracks,type:'playSmartRadio',id:arg.radio_id});},arg.autoplay,arg.index);}catch(e){DZ.catchException(e);}},setSongList:function(songList){try{player_light.loadSongs(songList);}catch(e){DZ.catchException(e);}}};;
DZ.notify={layer_container:null,messages:{'logged30':true,'notLogged30':true,'simultaneousAccess':true},already_displayed:[],display:function(message){try{var DZ_notify_messages=DZ.notify.messages;var DZ_request=DZ.request;var DZ_notify_already_displayed=DZ.notify.already_displayed;var DZ_notify_display_callback=DZ.notify.display_callback;if(typeof(DZ_notify_messages[message])=='undefined'){throw DZ.Exception('common');}
if(message=='logged30'||message=='notLogged30'){if(typeof(DZ_notify_already_displayed[message])!='undefined'&&DZ_notify_already_displayed[message]){return false;}
DZ_notify_already_displayed[message]=true;}
var layer_url=DZ.SETTING_HOST_SITE+"/plugins/layer.php";DZ_request._send({path:layer_url,path_args:["message="+message,"display=app","output=jsonp"],callback:DZ_notify_display_callback});}catch(e){DZ.catchException(e);}},display_callback:function(json){try{var html=(typeof(json)!='undefined'&&typeof(json.html)!='undefined')?json.html:null;if(html==null){throw DZ.Exception('common');}
if(DZ.notify.layer_container==null){DZ.notify.layer_container=document.createElement('div');document.getElementById('dz-root').appendChild(DZ.notify.layer_container);}
DZ.notify.layer_container.innerHTML=html;}catch(e){DZ.catchException(e);}},close_layer:function(){try{if(DZ.notify.layer_container==null){return false;}
DZ.notify.layer_container.innerHTML="";}catch(e){DZ.catchException(e);}}};;
DZ.request={callbacks:{},_send:function(options){try{var options=(typeof(options)=='undefined')?{}:options;var options=DZ.util.extend({path:null,path_args:[],callback_name:'callback',callback:function(){}},options);var callback_uniq_name=DZ.request.getUniqFctName();DZ.request.callbacks[callback_uniq_name]=options.callback;options.path_args.push(options.callback_name+"=DZ.request.callbacks."+callback_uniq_name);var script=document.createElement('script');script.onload=function(){document.getElementById('dz-root').removeChild(script);DZ.request.callbacks[callback_uniq_name]=null;delete DZ.request.callbacks[callback_uniq_name];}
script.src=options.path+'?'+options.path_args.join('&');document.getElementById('dz-root').appendChild(script);}catch(e){DZ.catchException(e);}},getUniqFctName:function(){try{var prefix="dzcb_";var retId;var formatSeed=function(seed,reqWidth){seed=parseInt(seed,10).toString(16);if(reqWidth<seed.length){return seed.slice(seed.length-reqWidth);}
if(reqWidth>seed.length){return Array(1+(reqWidth-seed.length)).join('0')+seed;}
return seed;};if(!this.php_js){this.php_js={};}
if(!this.php_js.uniqidSeed){this.php_js.uniqidSeed=Math.floor(Math.random()*0x75bcd15);}
this.php_js.uniqidSeed+=3;retId=prefix;retId+=formatSeed(parseInt(new Date().getTime()/1000,10),10);retId+=formatSeed(this.php_js.uniqidSeed,7);retId+="_"+Math.floor((Math.random()*10).toFixed(7)*100000000).toString();return retId;}catch(e){DZ.catchException(e);}}};;
DZ.util={extend:function(){try{var args=arguments;if(args.length==0||typeof(args[0])!='object'){throw DZ.Exception("extend arguments[0] is not an object");}
var object=args[0];for(var i=1;i<args.length;i++){if(typeof(args[i])!='object')continue;for(key in args[i]){object[key]=args[i][key];}}
return object;}catch(e){DZ.catchException(e);}}};;
DZ.init({initChannel:true});if(typeof(window.dzAsyncInit)!='undefined'){window.dzAsyncInit();};